---
apiVersion: v1
kind: Pod
metadata:
  name: quota-mem-cpu-2
  namespace: test 
spec: 
  containers:
  - name: www-quota
    image: nginx:1.14-alpine
    resources: 
      limits: 
        memory: "1Gi"
        cpu: "800m"
      requests:
        memory: "700Mi"
        cpu: "400m"

