---
apiVersion: v1
kind: Pod
metadata: 
  name: poddy 
  labels:
    app: whoami
spec: 
  containers: 
  - image: lucj/whoami
    name: whoami

---
apiVersion: v1
kind: Service
metadata:
   name: whoami
   labels:
     app: whoami
spec:
  selector:
    app: whoami
  type: ClusterIP
  ports: 
  - port: 80
    targetPort: 80

