---
apiVersion: v1
kind: Service
metadata:
  name: logstash
spec:
  type: NodePort
  ports:
    - port: 8080
      name: logstash
      targetPort: 8080
      nodePort: 31500
  selector:
    app: logstash

